### ISSUE TITLE
Add raw MUA data to DataJoint and NWB

### ISSUE THREAD

**Issue by rly** [vathes/DJ-NWB-Li-Daie-2015-2016#11]
The unsorted MUA data per session by channel and trial are available at CRCNS. It would be useful for users to have this data available in DataJoint and the exported NWB files in case they want to re-spike-sort the data or re-segment the waveforms using other methods. Using low threshold multi-units may reveal interesting, different results compared with the manually sorted data.

**Comment by ttngu207** [comment]
Including Raw data is beyond the scope of this project, inclusion of raw data is planned for the Mesoscale Activity Project (https://github.com/mesoscale-activity-map/map-ephys), where raw neuropixels data is to be included as part of NWB 2.0 export
