### ISSUE TITLE
Early lick should be stored as a boolean

### ISSUE THREAD

**Issue by rly** [vathes/DJ-NWB-Li-Daie-2015-2016#14]
The `early_lick` field of a trial is stored as a string ("early" or "no early"), but would be more effectively stored as a boolean. In the NWB export, this would also allow `early_lick` to be stored as a boolean in the trials table. 

https://github.com/vathes/DJ-NWB-Li-Daie-2015-2016/blob/ae69335a23e6a3c0c3809a54de5480baf8848712/pipeline/ingest/ingest_data_Li_2015.py#L118-L121

The EarlyLick schema says that there are three possible values, but the second value is never encountered in either of these datasets. Unless this schema is used for other datasets and there is a need to keep this consistent across datasets, I think EarlyLick should be a boolean instead of a varchar.

https://github.com/vathes/DJ-NWB-Li-Daie-2015-2016/blob/ae69335a23e6a3c0c3809a54de5480baf8848712/pipeline/experiment.py#L179-L189

**Comment by ttngu207** [comment]
It is more preferable to keep `early_lick` as a string instead of boolean, for the sake of consistency between other DataJoint pipelines as well as the data in original format. Some studies may have more labeling options than just `early` or `no early`.
