### ISSUE TITLE
NWB Export: Use nan as empty stop time instead of 5.0

### ISSUE THREAD

**Issue by rly** [vathes/DJ-NWB-Li-Daie-2015-2016#9]
In the below code, if there is no stop time associated with a trial, the value 5.0 is entered instead. Why 5.0? Using 5.0 would confuse any algorithms that uses this column to segment and visualize the data. np.nan seems more appropriate. If there is a reason behind using 5.0, please add it to the description of the `stop_time` column or the `trials` table. 

https://github.com/vathes/DJ-NWB-Li-Daie-2015-2016/blob/ae69335a23e6a3c0c3809a54de5480baf8848712/pipeline/export/datajoint_to_nwb.py#L221

**Comment by bendichter** [comment]
@ttngu207 We do not have permission to close this issue, but this has been resolved and should be closed.
